version: '3'

services:
    go_server_rpc:
      build: ./
      container_name: go_user_rpc
      environment:
         SERVICE_NAME: go_user_rpc
         SERVICE_TAGS: go_user_rpc,rpc,8080
      extra_hosts:
         - "www.52db.club:172.19.139.129"
      ports:
         - "8888:8888"
      volumes:
         - ../:/apps
         # 日志存放路径，需要同级目录创建本目录
         - ../logs:/apps/logs
      working_dir: /apps/go_user_rpc
      command: ./main


