apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-sc
reclaimPolicy: Retain
volumeBindingMode: Immediate
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-p-volume
  labels:
    type: app
spec:
  storageClassName: app-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /apps
    server: 139.224.132.234
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc-claim
spec:
  storageClassName: app-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: go-server-rpc
  name: go-server-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go-server-rpc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: go-server-rpc
    spec:
      containers:
      - args: ["./main"]
        env:
        - name: SERVICE_NAME
          value: go_user_rpc
        - name: SERVICE_TAGS
          value: go_user_rpc,rpc,8080
        image: xjyplayer/go-user-rpc:1.0.1
        imagePullPolicy: IfNotPresent
        name: go-user-rpc
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /apps/go_user_rpc
          subPath: go_user_rpc
          name: go-server-rpc-pvc
        - mountPath: /apps/log
          subPath: log
          name: go-server-rpc-pvc
        - mountPath: /apps/go_user
          subPath: go_user
          name: go-server-rpc-pvc
        workingDir: /apps/go_user_rpc
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: go-server-rpc-pvc
        persistentVolumeClaim:
          claimName: app-pvc-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: go-server-rpc
  name: go-server-rpc
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
    nodePort: 32000
  selector:
    io.kompose.service: go-server-rpc
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-user-rpc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
  - host: go.user.rpc.52db.club
    http:
      paths:
      - backend:
          serviceName: go-server-rpc
          servicePort: 8888
        path: /
  tls:
   - secretName: go-user-rpc-imroc-io-tls
     hosts:
       - go.user.rpc.52db.club


