// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protoc/user.proto

package user_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UserSessions) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *LoginRequest) Validate() error {
	return nil
}
func (this *LoginData) Validate() error {
	if this.UserSession != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserSession); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserSession", err)
		}
	}
	return nil
}
func (this *LoginResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *AddUserRequest) Validate() error {
	return nil
}
func (this *AddUserData) Validate() error {
	return nil
}
func (this *AddUserResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *DelUserRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	return nil
}
func (this *DelUserData) Validate() error {
	return nil
}
func (this *DelUserResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetUserListRequest) Validate() error {
	if !(this.Page > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Page", fmt.Errorf(`value '%v' must be greater than '0'`, this.Page))
	}
	if !(this.Size > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Size_", fmt.Errorf(`value '%v' must be greater than '0'`, this.Size))
	}
	return nil
}
func (this *GetUserListResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetUserListData) Validate() error {
	for _, item := range this.UserList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("UserList", err)
			}
		}
	}
	return nil
}
func (this *UserInfo) Validate() error {
	return nil
}
func (this *CheckUserStatusRequest) Validate() error {
	return nil
}
func (this *CheckUserStatusData) Validate() error {
	if this.UserSession != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UserSession); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UserSession", err)
		}
	}
	return nil
}
func (this *CheckUserStatusResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *RegisterRequest) Validate() error {
	return nil
}
func (this *RegisterData) Validate() error {
	return nil
}
func (this *RegisterResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *CheckUserAuthorityRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	if !(this.AuthorityId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("AuthorityId", fmt.Errorf(`value '%v' must be greater than '0'`, this.AuthorityId))
	}
	return nil
}
func (this *CheckUserAuthorityData) Validate() error {
	return nil
}
func (this *CheckUserAuthorityResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetUserAuthorityListRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	return nil
}
func (this *GetUserAuthorityListData) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetUserAuthorityListResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetAuthorityListRequest) Validate() error {
	return nil
}
func (this *GetAuthorityListData) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetAuthorityListResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *AddUserRoleRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	if !(this.RoleId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("RoleId", fmt.Errorf(`value '%v' must be greater than '0'`, this.RoleId))
	}
	return nil
}
func (this *AddUserRoleData) Validate() error {
	return nil
}
func (this *AddUserRoleResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *DelUserRoleRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	if !(this.RoleId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("RoleId", fmt.Errorf(`value '%v' must be greater than '0'`, this.RoleId))
	}
	return nil
}
func (this *DelUserRoleData) Validate() error {
	return nil
}
func (this *DelUserRoleResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetRoleListRequest) Validate() error {
	return nil
}
func (this *GetRoleListData) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetRoleListResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *GetUserRoleListRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	return nil
}
func (this *GetUserRoleListData) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetUserRoleListResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *LogoutRequest) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	return nil
}
func (this *LogoutResponse) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *LogoutData) Validate() error {
	return nil
}
